/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaclinica.view;

import br.com.sistemaclinica.model.Funcionario;

/**
 *
 * @author Alisson Dias
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Funcionario usuarioLogado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    // Apague o construtor antigo "public TelaPrincipal()" e substitua por este:
public TelaPrincipal(Funcionario usuario) {
    initComponents();
    this.usuarioLogado = usuario;

    // Define o título da janela para saudar o usuário
    this.setTitle("Sistema de Clínica - Usuário: " + this.usuarioLogado.getNome());

    // --- CONTROLE DE ACESSO AOS MENUS ---
    // Verificamos o perfil do usuário logado e habilitamos/desabilitamos os menus.
    if (this.usuarioLogado.getPerfil() != null) {
        // Exemplo para o menu de cadastro de funcionários
        menuItemFuncionarios.setEnabled(this.usuarioLogado.getPerfil().isListarFuncionario());

        // Exemplo para o menu de cadastro de pacientes
        menuItemPacientes.setEnabled(this.usuarioLogado.getPerfil().isListarPaciente());

        // Exemplo para o menu de agendamento de consultas
        menuItemAgendamento.setEnabled(this.usuarioLogado.getPerfil().isListarConsulta());

        // Exemplo para o menu de perfis (geralmente só para admin)
        menuItemPerfis.setEnabled(this.usuarioLogado.getPerfil().getNome().equalsIgnoreCase("Administrador"));
    }
}

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPacientesCadastrados = new javax.swing.JMenu();
        menuItemPerfis = new javax.swing.JMenu();
        menuItemFuncionarios = new javax.swing.JMenu();
        menuItemPacientes = new javax.swing.JMenu();
        menuItemAgendamento = new javax.swing.JMenu();
        menuItemConvenios = new javax.swing.JMenu();
        menuItemEspecialidades = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPacientesCadastrados.setText("Pacientes Cadastrados");
        MenuPacientesCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuPacientesCadastradosMouseClicked(evt);
            }
        });
        MenuPacientesCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPacientesCadastradosActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuPacientesCadastrados);

        menuItemPerfis.setText("Perfis");
        menuItemPerfis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemPerfisMouseClicked(evt);
            }
        });
        menuItemPerfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPerfisActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemPerfis);

        menuItemFuncionarios.setText("Funcionarios");
        menuItemFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemFuncionariosMouseClicked(evt);
            }
        });
        menuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemFuncionarios);

        menuItemPacientes.setText("Pacientes");
        menuItemPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemPacientesMouseClicked(evt);
            }
        });
        menuItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPacientesActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemPacientes);

        menuItemAgendamento.setText("Agendamento");
        menuItemAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemAgendamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemAgendamentoMouseEntered(evt);
            }
        });
        menuItemAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgendamentoActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemAgendamento);

        menuItemConvenios.setText("Cadastro Convenio");
        jMenuBar1.add(menuItemConvenios);

        menuItemEspecialidades.setText("Cadastrar Especialidade");
        menuItemEspecialidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemEspecialidadesMouseClicked(evt);
            }
        });
        menuItemEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspecialidadesActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuItemEspecialidades);

        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPacientesCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPacientesCadastradosActionPerformed
new TelaCadastroPaciente().setVisible(true);    
    }//GEN-LAST:event_MenuPacientesCadastradosActionPerformed

    private void MenuPacientesCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPacientesCadastradosMouseClicked
        TelaPacientesCadastrados telapacientescadastrados= new TelaPacientesCadastrados();
    telapacientescadastrados.setVisible(true);    
    // TODO add your handling code here:
    }//GEN-LAST:event_MenuPacientesCadastradosMouseClicked

    private void menuItemPerfisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPerfisMouseClicked
             TelaCadastroPerfil telapacientescadastrados = new TelaCadastroPerfil();
    telapacientescadastrados.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPerfisMouseClicked

    private void menuItemFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemFuncionariosMouseClicked
         TelaCadastroFuncionario telapacientescadastrados = new TelaCadastroFuncionario();
    telapacientescadastrados.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_menuItemFuncionariosMouseClicked

    private void menuItemAgendamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemAgendamentoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAgendamentoMouseEntered

    private void menuItemAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemAgendamentoMouseClicked
          TelaAgendamentoConsulta telapacientescadastrados = new TelaAgendamentoConsulta();
    telapacientescadastrados.setVisible(true);  
        
// TODO add your handling code here:
    }//GEN-LAST:event_menuItemAgendamentoMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        TelaLogin telapacientescadastrados = new TelaLogin();
        telapacientescadastrados.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void menuItemPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPacientesMouseClicked
        TelaCadastroPaciente telapacientescadastrados = new TelaCadastroPaciente();
        telapacientescadastrados.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPacientesMouseClicked

    private void menuItemPerfisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPerfisActionPerformed
new TelaCadastroPerfil().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPerfisActionPerformed

    private void menuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionariosActionPerformed
new TelaCadastroFuncionario().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemFuncionariosActionPerformed

    private void menuItemAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgendamentoActionPerformed
new TelaAgendamentoConsulta().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemAgendamentoActionPerformed

    private void menuItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPacientesActionPerformed
new TelaCadastroPaciente().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemPacientesActionPerformed

    private void menuItemEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspecialidadesActionPerformed
      new TelaCadastroEspecialidade().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEspecialidadesActionPerformed

    private void menuItemEspecialidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemEspecialidadesMouseClicked
new TelaCadastroEspecialidade().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEspecialidadesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuPacientesCadastrados;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuItemAgendamento;
    private javax.swing.JMenu menuItemConvenios;
    private javax.swing.JMenu menuItemEspecialidades;
    private javax.swing.JMenu menuItemFuncionarios;
    private javax.swing.JMenu menuItemPacientes;
    private javax.swing.JMenu menuItemPerfis;
    // End of variables declaration//GEN-END:variables
}
