/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaclinica.view;

import br.com.sistemaclinica.dao.ConvenioDAO;
import br.com.sistemaclinica.dao.FuncionarioDAO;
import br.com.sistemaclinica.model.Convenio;
import br.com.sistemaclinica.model.Funcionario;
import br.com.sistemaclinica.model.TipoFuncionario;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
/**
 *
 * @author Alisson Dias
 */
public class TelaCadastroConvenio extends javax.swing.JFrame {
       
    private int idConvenioSelecionado = 0; // <<-- ADICIONE ESTA LINHA
    
    private void tblConveniosValueChanged(javax.swing.event.ListSelectionEvent evt) {                                             
    if (!evt.getValueIsAdjusting()) {
        int linhaSelecionada = tblConvenios.getSelectedRow();
        if (linhaSelecionada != -1) {
            // Pega o ID da coluna 0, converte para Integer e guarda na nossa variável
            idConvenioSelecionado = Integer.parseInt(tblConvenios.getValueAt(linhaSelecionada, 0).toString()); // <<-- ADICIONE ESTA LINHA

            // Pega os outros dados e preenche os campos
            String nome = tblConvenios.getValueAt(linhaSelecionada, 1).toString();
            String descricao = tblConvenios.getValueAt(linhaSelecionada, 2).toString();
            

            txtNomeConvenio.setText(nome);
            txaDescricaoConvenio.setText(descricao);
        
        }
    }
}
    
    private void carregarTabela() {
      ConvenioDAO dao = new ConvenioDAO();
    List<Convenio> lista = dao.listarTodos();
    DefaultTableModel modelo = (DefaultTableModel) tblConvenios.getModel();
    modelo.setRowCount(0);
    modelo.setColumnIdentifiers(new Object[]{"ID", "Nome", "Descrição"});
    for (Convenio c : lista) {
        modelo.addRow(new Object[]{c.getId(), c.getNome(), c.getDescricao()});
    }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroConvenio.class.getName());

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroConvenio() {
        initComponents();
        tblConvenios.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {

        @Override
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            // Este método é chamado toda vez que a seleção muda.
            // Dentro dele, nós simplesmente chamamos o nosso outro método que faz o trabalho pesado.
            tblConveniosValueChanged(evt);
        }

            
    });
        
    
       carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNomeConvenio = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConvenios = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDescricaoConvenio = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nome:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tblConvenios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConvenios);

        btnNovo.setText("Limpar Campos");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(255, 51, 51));
        btnDeletar.setText("Apagar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição:");

        txaDescricaoConvenio.setColumns(20);
        txaDescricaoConvenio.setRows(5);
        jScrollPane2.setViewportView(txaDescricaoConvenio);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeletar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNomeConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(378, 378, 378)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnDeletar)
                    .addComponent(btnCancelar))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
 // Coleta todos os dados da tela
    Convenio Convenio = new Convenio();
    Convenio.setNome(txtNomeConvenio.getText());
    Convenio.setDescricao(txaDescricaoConvenio.getText());

   
 

    // --- AQUI ESTÁ A LÓGICA ---
    try {
        ConvenioDAO dao = new ConvenioDAO();

        // Se idFuncionarioSelecionado é 0, então é um NOVO cadastro
        if (idConvenioSelecionado == 0) {
            dao.cadastrar(Convenio);
            javax.swing.JOptionPane.showMessageDialog(this, "Cônvenio cadastrado com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } 
        // Senão, é uma ATUALIZAÇÃO
        else {
            // Define o ID no objeto para que o DAO saiba quem atualizar
            Convenio.setId(idConvenioSelecionado);
            dao.atualizar(Convenio);
            javax.swing.JOptionPane.showMessageDialog(this, "Cônvenio atualizado com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        // Após salvar (seja criando ou atualizando), limpa o formulário e recarrega a tabela
        btnNovoActionPerformed(null); // Chama a ação do botão Novo para limpar tudo
        carregarTabela();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar:\n" + e.getMessage(), "Erro no Banco de Dados", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
  // Limpa todos os campos de texto
    txtNomeConvenio.setText("");
   
    txaDescricaoConvenio.setText("");
  

    // Habilita os campos que foram desabilitados
   
   

    // Remove a seleção da tabela
    tblConvenios.clearSelection();

    // Zera nossa variável de controle. Este é o passo mais importante!
    idConvenioSelecionado = 0;        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
   // 1. Verifica se algum funcionário foi selecionado na tabela.
        if (idConvenioSelecionado == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um Cônvenio na tabela para excluir.", "Nenhum funcionário selecionado", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Pede confirmação ao usuário. Este é um passo MUITO importante para evitar exclusões acidentais.
        int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este Cônvenio?\nEsta ação não pode ser desfeita.", "Confirmação de Exclusão", javax.swing.JOptionPane.YES_NO_OPTION);

        // 3. Se o usuário clicou em "Sim"...
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Cria o DAO e chama o método deletar, passando o ID que já guardamos.
                ConvenioDAO dao = new ConvenioDAO();
                dao.deletar(idConvenioSelecionado);

                // Mostra a mensagem de sucesso.
                javax.swing.JOptionPane.showMessageDialog(this, "Cônvenio excluído com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Limpa o formulário e recarrega a tabela para refletir a exclusão.
                btnNovoActionPerformed(null);
                carregarTabela();

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir Cônvenio:\n" + e.getMessage(), "Erro no Banco de Dados", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
  // Este comando fecha a janela ATUAL e libera seus recursos da memória,
    // revelando a tela que estava por baixo (a TelaPrincipal).
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroConvenio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblConvenios;
    private javax.swing.JTextArea txaDescricaoConvenio;
    private javax.swing.JTextField txtNomeConvenio;
    // End of variables declaration//GEN-END:variables
}
