/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.sistemaclinica.view;

import br.com.sistemaclinica.dao.ProntuarioDAO;
import br.com.sistemaclinica.model.Paciente;
import br.com.sistemaclinica.model.Prontuario;

/**
 *
 * @author Alisson Dias
 */
public class TelaProntuario extends javax.swing.JFrame {
    
    
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaProntuario.class.getName());

    private final int pacienteId;
    private Prontuario prontuarioAtual;

    private TelaProntuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
            
           
  private void carregarProntuario() {
    ProntuarioDAO dao = new ProntuarioDAO();
    this.prontuarioAtual = dao.buscarPorPacienteId(this.pacienteId);

    // Se o paciente já tem um prontuário, preenchemos os campos
    if (this.prontuarioAtual != null) {
        txaReceituario.setText(prontuarioAtual.getReceituario());
        txaExames.setText(prontuarioAtual.getExames());
        txaObservacoes.setText(prontuarioAtual.getObservacoes());
    } 
 // Se for nulo, significa que é a primeira vez, então os campos ficam em branco.
}

    public TelaProntuario(int pacienteId, String pacienteNome) {
        initComponents();
        this.pacienteId = pacienteId;

        // Define o título da janela e o nome no label
        this.setTitle("Prontuário de " + pacienteNome);
        lblNomePaciente.setText("Prontuário de: " + pacienteNome);
        carregarProntuario();
    }   
    /**
     * Creates new form TelaProntuario
     */
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomePaciente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvarProntuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaReceituario = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaExames = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaObservacoes = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Receituario");

        jLabel3.setText("Exames");

        btnSalvarProntuario.setText("Salvar");
        btnSalvarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProntuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Observacoes");

        txaReceituario.setColumns(20);
        txaReceituario.setRows(5);
        jScrollPane5.setViewportView(txaReceituario);

        txaExames.setColumns(20);
        txaExames.setRows(5);
        jScrollPane2.setViewportView(txaExames);

        txaObservacoes.setColumns(20);
        txaObservacoes.setRows(5);
        jScrollPane6.setViewportView(txaObservacoes);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnSalvarProntuario)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNomePaciente)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvarProntuario))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProntuarioActionPerformed
 // Se o prontuário ainda não existe, criamos um novo objeto
    if (this.prontuarioAtual == null) {
        this.prontuarioAtual = new Prontuario();
        // Precisamos associar este novo prontuário ao paciente correto
        Paciente p = new Paciente();
        p.setId(this.pacienteId);
        this.prontuarioAtual.setPaciente(p);
    }

    // Pega os textos da tela e atualiza o objeto
    this.prontuarioAtual.setReceituario(txaReceituario.getText());
    this.prontuarioAtual.setExames(txaExames.getText());
    this.prontuarioAtual.setObservacoes(txaObservacoes.getText());

    // Chama o método "salvar" inteligente do DAO
    ProntuarioDAO dao = new ProntuarioDAO();
    try {
        dao.salvar(this.prontuarioAtual);
        javax.swing.JOptionPane.showMessageDialog(this, "Prontuário salvo com sucesso!");
        this.dispose(); // Fecha a tela de prontuário após salvar
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar o prontuário:\n" + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarProntuarioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        TelaPacientesCadastrados telapacientescadastrados = new TelaPacientesCadastrados();
    telapacientescadastrados.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaProntuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarProntuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblNomePaciente;
    private javax.swing.JTextArea txaExames;
    private javax.swing.JTextArea txaObservacoes;
    private javax.swing.JTextArea txaReceituario;
    // End of variables declaration//GEN-END:variables
}
