/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

import Login.LoginTela;

/**
 *
 * @author Alisson Dias
 */
public class Agenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Agenda.class.getName());

    /**
     * Creates new form Menumain
     */
    public Agenda() {
        initComponents();
    }






// --- Para o JMenuItem "Cadastrar Especialidades" (Abrir CadastrarEspecialidades.java) ---


/*
private void ConsultasTableMouseClicked(java.awt.event.MouseEvent evt) {
    // Exemplo: Clicar duas vezes na linha para abrir detalhes
    if (evt.getClickCount() == 2) {
        int selectedRow = ConsultasTable.getSelectedRow();
        if (selectedRow != -1) {
            // Obter dados da linha selecionada para passar para a tela de detalhes
            // Por exemplo: String idConsulta = ConsultasTable.getValueAt(selectedRow, 0).toString();
            // TelaDetalhesConsulta telaDetalhes = new TelaDetalhesConsulta(idConsulta);
            // telaDetalhes.setVisible(true);
        }
    }
}
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultasTable = new javax.swing.JTable();
        EditarAgendaButton = new javax.swing.JButton();
        ListarPorRetornoButton = new javax.swing.JButton();
        ListarTodosButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        CadastrarPacientesMenu = new javax.swing.JMenu();
        AgendarConsultasMenu = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        EspecialidadesMenu = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        ListarEspecialidadesMenu = new javax.swing.JMenu();
        AgendaMenu = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConsultasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Paciente", "Data", "Hora", "Médico", "Especialidade", "Cônvenio", "retorno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ConsultasTable);
        if (ConsultasTable.getColumnModel().getColumnCount() > 0) {
            ConsultasTable.getColumnModel().getColumn(4).setResizable(false);
        }

        EditarAgendaButton.setText("Editar agenda");

        ListarPorRetornoButton.setText("Listar Por Retono");

        ListarTodosButton.setText("Listar Todos");

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacientesCadastradosMenuMouseClicked(evt);
            }
        });
        PacientesMenu.add(PacientesCadastradosMenu);

        CadastrarPacientesMenu.setText("Cadastrar Paciente");
        CadastrarPacientesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarPacientesMenuMouseClicked(evt);
            }
        });
        PacientesMenu.add(CadastrarPacientesMenu);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultasMenu.setText("Agendar Consultas");
        AgendarConsultasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarConsultasMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(AgendarConsultasMenu);

        MedicosMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        CadastrarMedicoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMedicoMenuMouseClicked(evt);
            }
        });
        MedicosMenu.add(CadastrarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicosCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicosCadastradosMenuMouseClicked(evt);
            }
        });
        MedicosMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicosMenu);

        EspecialidadesMenu.setText("Especialidades");

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidades");
        CadastrarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarEspecialidadesMenuMouseClicked(evt);
            }
        });
        EspecialidadesMenu.add(CadastrarEspecialidadesMenu);

        ListarEspecialidadesMenu.setText("Listar Especialidades");
        ListarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarEspecialidadesMenuMouseClicked(evt);
            }
        });
        EspecialidadesMenu.add(ListarEspecialidadesMenu);

        jMenuBar1.add(EspecialidadesMenu);

        AgendaMenu.setText("Agenda");
        AgendaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendaMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(AgendaMenu);

        SairMenu.setText("Sair");
        SairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ListarTodosButton)
                .addGap(18, 18, 18)
                .addComponent(ListarPorRetornoButton)
                .addGap(33, 33, 33)
                .addComponent(EditarAgendaButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarAgendaButton)
                    .addComponent(ListarTodosButton)
                    .addComponent(ListarPorRetornoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PacientesCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PacientesCadastradosMenuMouseClicked
      PacientesCadastradosAtendente PacientesCadastrados = new PacientesCadastradosAtendente ();
    PacientesCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_PacientesCadastradosMenuMouseClicked

    private void CadastrarPacientesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarPacientesMenuMouseClicked
         CadastrarPaciente CadastrarPacientes = new CadastrarPaciente();
    CadastrarPacientes.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_CadastrarPacientesMenuMouseClicked

    private void AgendarConsultasMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgendarConsultasMenuMouseClicked
    
   AgendarCosulta AgendarCosulta  = new AgendarCosulta();
    AgendarCosulta.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_AgendarConsultasMenuMouseClicked

    private void CadastrarMedicoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMedicoMenuMouseClicked
       CadastrarMedico  CadastrarMedico = new  CadastrarMedico();
     CadastrarMedico.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_CadastrarMedicoMenuMouseClicked

    private void MedicosCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicosCadastradosMenuMouseClicked
        MedicosCadastradosAtendente MedicosCadastrados= new MedicosCadastradosAtendente();
    MedicosCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_MedicosCadastradosMenuMouseClicked

    private void CadastrarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarEspecialidadesMenuMouseClicked
        Cadastrarespecialidades Cadastrarespecialidades  =  new Cadastrarespecialidades();
    Cadastrarespecialidades.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_CadastrarEspecialidadesMenuMouseClicked

    private void ListarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListarEspecialidadesMenuMouseClicked
       EspecialidadeCadastradas  EspecialidadeCadastradas = new EspecialidadeCadastradas();
    EspecialidadeCadastradas.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_ListarEspecialidadesMenuMouseClicked

    private void AgendaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgendaMenuMouseClicked
    Agenda Agenda = new Agenda();
    Agenda.setVisible(true); // Torna a tela visível
    this.dispose();
    }//GEN-LAST:event_AgendaMenuMouseClicked

    private void SairMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMenuMouseClicked
            String[] options = {"Sim", "Não"};
            int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                    "Tem certeza que deseja voltar ao login?",
                    "Confirmar Saída", javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null, options, options[0]);
            if (confirm == 0) {
                LoginTela LoginTela = new LoginTela();
                LoginTela.setVisible(true); // Torna a tela visível
                this.dispose();
            }
    }//GEN-LAST:event_SairMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Agenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgendaMenu;
    private javax.swing.JMenu AgendarConsultasMenu;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JMenu CadastrarPacientesMenu;
    private javax.swing.JTable ConsultasTable;
    private javax.swing.JButton EditarAgendaButton;
    private javax.swing.JMenu EspecialidadesMenu;
    private javax.swing.JMenu ListarEspecialidadesMenu;
    private javax.swing.JButton ListarPorRetornoButton;
    private javax.swing.JButton ListarTodosButton;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}

