/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

import Daos.EspecialidadeDaoCad;
import Daos.MedicoDaos;
import Entidades.Especialidade;
import Entidades.Medico;
import Login.LoginTela;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisson Dias
 */
public class CadastrarMedico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarMedico.class.getName());
    private List<Especialidade> todasEspecialidadesDisponiveis;
    
    

    /**
     * Creates new form Menumain
     */
    public CadastrarMedico() {
        initComponents();
        
        setLocationRelativeTo(null);

        carregarEstadoCivilComboBox();
        carregarSexoComboBox();
        carregarEspecialidadesComboBox(); 
    
       
        PacientesCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacientesCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarPacienteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarPacientesMenuMouseClicked(evt);
            }
        });
        AgendarConsultaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarConsultasMenuMouseClicked(evt);
            }
        });
        AgendarRetornoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarRetornoMenuMouseClicked(evt);
            }
        });
        CadastrarMedicoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMedicoMenuMouseClicked(evt);
            }
        });
        MedicosCadstradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicosCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarEspecialidadesMenuMouseClicked(evt);
            }
        });
        ListarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarEspecialidadesMenuMouseClicked(evt);
            }
        });
        AgendaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendaMenuMouseClicked(evt);
            }
        });
        SairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMenuMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NomeTextField = new javax.swing.JTextField();
        CpfTextField = new javax.swing.JTextField();
        EnderecoTextField = new javax.swing.JTextField();
        CrmTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ObservacoesTextArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        DatadeNascimentoTextField = new javax.swing.JTextField();
        TelefoneTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EstadoCivilComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        SalvarButton = new javax.swing.JButton();
        AtendeConvenioCheckBox = new javax.swing.JCheckBox();
        SexoComboBox = new javax.swing.JComboBox<>();
        EspecialidadeComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacienteMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        CadastrarPacienteMenu = new javax.swing.JMenu();
        AgendarConsultaMenu = new javax.swing.JMenu();
        AgendarRetornoMenu = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadstradosMenu = new javax.swing.JMenu();
        EspeciialidadesMenu = new javax.swing.JMenu();
        ListarEspecialidadesMenu = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        AgendaMenu = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Cpf");

        jLabel3.setText("Telefone");

        jLabel4.setText("Endereço");

        jLabel5.setText("Sexo");

        jLabel6.setText("Estado Civil");

        jLabel7.setText("CRM ");

        jLabel8.setText("Especialidade:");

        jLabel9.setText("Observações:");

        ObservacoesTextArea.setColumns(20);
        ObservacoesTextArea.setRows(5);
        jScrollPane1.setViewportView(ObservacoesTextArea);

        jLabel10.setText("Data de Nascimento:");

        jLabel11.setText("Atende Cônvenio ?");

        EstadoCivilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Cancelar");

        SalvarButton.setText("Salvar");
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonActionPerformed(evt);
            }
        });

        AtendeConvenioCheckBox.setText("jCheckBox1");

        SexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PacienteMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacienteMenu.add(PacientesCadastradosMenu);

        CadastrarPacienteMenu.setText("Cadastrar Paciente");
        PacienteMenu.add(CadastrarPacienteMenu);

        jMenuBar1.add(PacienteMenu);

        AgendarConsultaMenu.setText("Agendar Consultas ");
        jMenuBar1.add(AgendarConsultaMenu);

        AgendarRetornoMenu.setText("Agendar retorno");
        jMenuBar1.add(AgendarRetornoMenu);

        MedicosMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        MedicosMenu.add(CadastrarMedicoMenu);

        MedicosCadstradosMenu.setText("Médicos Cadastrados");
        MedicosMenu.add(MedicosCadstradosMenu);

        jMenuBar1.add(MedicosMenu);

        EspeciialidadesMenu.setText("Especialidades");

        ListarEspecialidadesMenu.setText("Listar Especialidades");
        EspeciialidadesMenu.add(ListarEspecialidadesMenu);

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidades");
        EspeciialidadesMenu.add(CadastrarEspecialidadesMenu);

        jMenuBar1.add(EspeciialidadesMenu);

        AgendaMenu.setText("Agenda");
        jMenuBar1.add(AgendaMenu);

        SairMenu.setText("Sair");
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(CpfTextField)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EnderecoTextField)
                                        .addComponent(TelefoneTextField)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CrmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EstadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(83, 83, 83))))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DatadeNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AtendeConvenioCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EspecialidadeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SalvarButton)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(AtendeConvenioCheckBox))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TelefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(EnderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(SexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EstadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CrmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(DatadeNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(EspecialidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SalvarButton))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void PacientesCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
      PacientesCadastradosAtendente PacientesCadastrados = new PacientesCadastradosAtendente ();
    PacientesCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void CadastrarPacientesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
         CadastrarPaciente CadastrarPacientes = new CadastrarPaciente();
    CadastrarPacientes.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void AgendarConsultasMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                  
    
   AgendarCosulta AgendarCosulta  = new AgendarCosulta();
    AgendarCosulta.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                 

    private void AgendarRetornoMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                
     Agendarretorno Agendarretorno = new Agendarretorno();
    Agendarretorno.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                               

    private void CadastrarMedicoMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                 
       CadastrarMedico  CadastrarMedico = new  CadastrarMedico();
     CadastrarMedico.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                

    private void MedicosCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        MedicosCadastradosAtendente MedicosCadastrados= new MedicosCadastradosAtendente();
    MedicosCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void CadastrarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                         
        Cadastrarespecialidades Cadastrarespecialidades  =  new Cadastrarespecialidades();
    Cadastrarespecialidades.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                        

    private void ListarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
       EspecialidadeCadastradas  EspecialidadeCadastradas = new EspecialidadeCadastradas();
    EspecialidadeCadastradas.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void AgendaMenuMouseClicked(java.awt.event.MouseEvent evt) {                                        
    Agenda Agenda = new Agenda();
    Agenda.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                       

    private void SairMenuMouseClicked(java.awt.event.MouseEvent evt) {
        String[] options = {"Sim", "Não"};
        int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                "Tem certeza que deseja voltar ao login?",
                "Confirmar Saída", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (confirm == 0) {
            LoginTela LoginTela = new LoginTela();
            LoginTela.setVisible(true); // Torna a tela visível
            this.dispose();
        }
    }   
    
  private void carregarEspecialidadesComboBox() {
        EspecialidadeDaoCad especialidadeDAO = new EspecialidadeDaoCad(); // Verifique o nome do seu DAO!
        todasEspecialidadesDisponiveis = especialidadeDAO.buscarTodasEspecialidades(); // Busca objetos Especialidade

        // Usamos DefaultComboBoxModel para preencher o JComboBox
        DefaultComboBoxModel<Especialidade> model = new DefaultComboBoxModel<>();

        // Adiciona um item padrão (recomendado)
        model.addElement(null); // Adiciona um item nulo que pode ser interpretado como "Selecione"
                                // Ou crie um objeto Especialidade fake: new Especialidade("", "Selecione")
        
        // Adiciona as especialidades do banco ao modelo
        for (Especialidade esp : todasEspecialidadesDisponiveis) {
            model.addElement(esp); // Adiciona o objeto Especialidade ao modelo do ComboBox
        }
        
        // Define o modelo no seu JComboBox
        EspecialidadeComboBox.setModel(model); // Use o nome da sua variável JComboBox (ex: cmbEspecialidade)
       

    }
    
    
    private void carregarEstadoCivilComboBox() {
        EstadoCivilComboBox.removeAllItems();
        EstadoCivilComboBox.addItem("Solteiro");
        EstadoCivilComboBox.addItem("Casado");
        EstadoCivilComboBox.addItem("Divorciado");
        EstadoCivilComboBox.setSelectedIndex(0);
    }
    
     private void carregarSexoComboBox() {
        SexoComboBox.removeAllItems();
        SexoComboBox.addItem("Masculino");
        SexoComboBox.addItem("Feminino");
        SexoComboBox.addItem("Outro");
        SexoComboBox.setSelectedIndex(0);
    }
    
    
    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonActionPerformed
    try {
            // 1. Coletar dados do formulário
            String nome = NomeTextField.getText().trim();
            String cpf = CpfTextField.getText().trim();
            String crm = CrmTextField.getText().trim();
            String dataNascimento = DatadeNascimentoTextField.getText().trim();
            String endereco = EnderecoTextField.getText().trim();
            String observacoes = ObservacoesTextArea.getText().trim();

            String estadoCivil = (String) EstadoCivilComboBox.getSelectedItem();
            String sexo = (String) SexoComboBox.getSelectedItem();
            String convenio = AtendeConvenioCheckBox.isSelected() ? "S" : "N";

            // 2. Validações básicas (adicione mais conforme necessário)
            if (nome.isEmpty() || cpf.isEmpty() || crm.isEmpty() || dataNascimento.isEmpty() || endereco.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos obrigatórios (Nome, CPF, CRM, Data Nasc., Endereço).", "Campos Vazios", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (estadoCivil == null || estadoCivil.equals("Selecione")) {
                 JOptionPane.showMessageDialog(this, "Por favor, selecione o Estado Civil.", "Seleção Inválida", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (sexo == null || sexo.equals("Selecione")) {
                 JOptionPane.showMessageDialog(this, "Por favor, selecione o Sexo.", "Seleção Inválida", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Opcional: Remover caracteres não numéricos de CPF e CRM se for salvar apenas números
            cpf = cpf.replaceAll("[^0-9]", "");
            crm = crm.replaceAll("[^0-9]", "");
            
            // Validações de tamanho (se a coluna for VARCHAR(11) para CPF, por exemplo)
            if (cpf.length() != 11) {
                JOptionPane.showMessageDialog(this, "CPF deve ter 11 dígitos.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }
             if (crm.length() > 9 || crm.isEmpty()) { // CRM tem até 9 dígitos no Brasil
                JOptionPane.showMessageDialog(this, "CRM inválido. Deve ter até 9 dígitos numéricos.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                return;
            }
          
            Especialidade especialidadeSelecionada = (Especialidade) EspecialidadeComboBox.getSelectedItem();

                if (especialidadeSelecionada == null || especialidadeSelecionada.getCbo().isEmpty()) { // Se o placeholder for null ou CBO vazio
                JOptionPane.showMessageDialog(this, "Por favor, selecione uma especialidade da lista.", "Seleção Inválida", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 4. Criar o objeto Medico
            Medico novoMedico = new Medico(
                nome, cpf, crm, dataNascimento, estadoCivil, sexo,
                convenio, endereco, observacoes, especialidadeSelecionada
            );

            // 5. Instanciar e chamar o MedicoDAO para adicionar
            MedicoDaos medicoDAO = new MedicoDaos();
            medicoDAO.adicionar(novoMedico);

            // 6. Opcional: Limpar campos após salvar com sucesso
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado ao cadastrar médico: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Imprime o stack trace no console do NetBeans para depuração
        }
    
    // TODO add your handling code here:
    }//GEN-LAST:event_SalvarButtonActionPerformed

     private void limparCampos() {
        NomeTextField.setText("");
        CpfTextField.setText("");
        CrmTextField.setText("");
        DatadeNascimentoTextField.setText("");
        EnderecoTextField.setText("");
        ObservacoesTextArea.setText("");
        EstadoCivilComboBox.setSelectedIndex(0);
        SexoComboBox.setSelectedIndex(0);
        AtendeConvenioCheckBox.setSelected(false);
        EspecialidadeComboBox.setSelectedIndex(0); // Limpa o ComboBox de especialidade.clearSelection(); // Limpa as seleções do JList
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgendaMenu;
    private javax.swing.JMenu AgendarConsultaMenu;
    private javax.swing.JMenu AgendarRetornoMenu;
    private javax.swing.JCheckBox AtendeConvenioCheckBox;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JMenu CadastrarPacienteMenu;
    private javax.swing.JTextField CpfTextField;
    private javax.swing.JTextField CrmTextField;
    private javax.swing.JTextField DatadeNascimentoTextField;
    private javax.swing.JTextField EnderecoTextField;
    private javax.swing.JComboBox<Entidades.Especialidade> EspecialidadeComboBox;
    private javax.swing.JMenu EspeciialidadesMenu;
    private javax.swing.JComboBox<String> EstadoCivilComboBox;
    private javax.swing.JMenu ListarEspecialidadesMenu;
    private javax.swing.JMenu MedicosCadstradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JTextArea ObservacoesTextArea;
    private javax.swing.JMenu PacienteMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JComboBox<String> SexoComboBox;
    private javax.swing.JTextField TelefoneTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
