/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

import Login.LoginTela;
import Daos.EspecialidadeDAO;
import Entidades.Especialidade;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
/**
 *
 * @author Alisson Dias
 */
public class Cadastrarespecialidades extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastrarespecialidades.class.getName());

    /**
     * Creates new form Menumain
     */
    public Cadastrarespecialidades() {
        initComponents();
        // Listeners dos menus
        PacientesCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacientesCadastradosMenuMouseClicked(evt);
            }
        });
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarPacientesMenuMouseClicked(evt);
            }
        });
        AgendarConsultasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarConsultasMenuMouseClicked(evt);
            }
        });
      
        CadastrarMedicoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMedicoMenuMouseClicked(evt);
            }
        });
        MedicosCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicosCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarEspecialidadesMenuMouseClicked(evt);
            }
        });
        ListarEspelidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarEspecialidadesMenuMouseClicked(evt);
            }
        });
        AgendaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendaMenuMouseClicked(evt);
            }
        });
        SairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMenuMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        DataAddLabel = new javax.swing.JLabel();
        DataAddMenu = new javax.swing.JTextField();
        EspecialidadeLabel = new javax.swing.JLabel();
        AtendeconveniolabelMenu = new javax.swing.JLabel();
        CBOlabel = new javax.swing.JLabel();
        EspelialidadesTextField = new javax.swing.JTextField();
        CBOTextField = new javax.swing.JTextField();
        AtendeConvenioCheckbox = new javax.swing.JCheckBox();
        CancelarButton = new javax.swing.JButton();
        AdicionarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        AgendarConsultasMenu = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        Especialidades = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        ListarEspelidadesMenu = new javax.swing.JMenu();
        AgendaMenu = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataAddLabel.setText("Data de adição ");

        DataAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataAddMenuActionPerformed(evt);
            }
        });

        EspecialidadeLabel.setText("Especialidade:");

        CBOlabel.setText("CBO:");

        EspelialidadesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspelialidadesTextFieldActionPerformed(evt);
            }
        });

        CBOTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOTextFieldActionPerformed(evt);
            }
        });

        AtendeConvenioCheckbox.setText("Atende por convênio ?");
        AtendeConvenioCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendeConvenioCheckboxActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");

        AdicionarButton.setText("Adicionar");
        AdicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarButtonActionPerformed(evt);
            }
        });

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCadastradosMenu);

        jMenu2.setText("Cadastrar Paciente");
        PacientesMenu.add(jMenu2);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultasMenu.setText("Agendar Consultas");
        jMenuBar1.add(AgendarConsultasMenu);

        MedicosMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        MedicosMenu.add(CadastrarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicosMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicosMenu);

        Especialidades.setText("Especialidades");

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidade");
        Especialidades.add(CadastrarEspecialidadesMenu);

        ListarEspelidadesMenu.setText("Listar Especialidades");
        Especialidades.add(ListarEspelidadesMenu);

        jMenuBar1.add(Especialidades);

        AgendaMenu.setText("Agenda");
        jMenuBar1.add(AgendaMenu);

        SairMenu.setText("Sair");
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AtendeConvenioCheckbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AtendeconveniolabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DataAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AdicionarButton)
                                .addGap(34, 34, 34)
                                .addComponent(CancelarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EspecialidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EspelialidadesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                                .addComponent(CBOlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataAddLabel)
                    .addComponent(DataAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecialidadeLabel)
                    .addComponent(CBOlabel)
                    .addComponent(EspelialidadesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AtendeconveniolabelMenu)
                    .addComponent(AtendeConvenioCheckbox))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarButton)
                    .addComponent(AdicionarButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
   

    
     private void PacientesCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {
      PacientesCadastradosAtendente PacientesCadastrados = new PacientesCadastradosAtendente ();
    PacientesCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void CadastrarPacientesMenuMouseClicked(java.awt.event.MouseEvent evt) {
         CadastrarPaciente CadastrarPacientes = new CadastrarPaciente();
    CadastrarPacientes.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void AgendarConsultasMenuMouseClicked(java.awt.event.MouseEvent evt) {

   AgendarCosulta AgendarCosulta  = new AgendarCosulta();
    AgendarCosulta.setVisible(true); // Torna a tela visível
    this.dispose();
    }

   

    private void CadastrarMedicoMenuMouseClicked(java.awt.event.MouseEvent evt) {
       CadastrarMedico  CadastrarMedico = new  CadastrarMedico();
     CadastrarMedico.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void MedicosCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {
        MedicosCadastradosAtendente MedicosCadastrados= new MedicosCadastradosAtendente();
    MedicosCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void CadastrarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {
        Cadastrarespecialidades Cadastrarespecialidades  =  new Cadastrarespecialidades();
    Cadastrarespecialidades.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void ListarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {
       EspecialidadeCadastradas  EspecialidadeCadastradas = new EspecialidadeCadastradas();
    EspecialidadeCadastradas.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void AgendaMenuMouseClicked(java.awt.event.MouseEvent evt) {
    Agenda Agenda = new Agenda();
    Agenda.setVisible(true); // Torna a tela visível
    this.dispose();
    }

    private void SairMenuMouseClicked(java.awt.event.MouseEvent evt) {
        String[] options = {"Sim", "Não"};
        int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                "Tem certeza que deseja voltar ao login?",
                "Confirmar Saída", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (confirm == 0) {
            LoginTela LoginTela = new LoginTela();
            LoginTela.setVisible(true); // Torna a tela visível
            this.dispose();
        }
    }

    private void DataAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataAddMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataAddMenuActionPerformed

    private void CBOTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOTextFieldActionPerformed

    private void AtendeConvenioCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendeConvenioCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtendeConvenioCheckboxActionPerformed

    private void EspelialidadesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspelialidadesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspelialidadesTextFieldActionPerformed

    private void AdicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarButtonActionPerformed
 // 1. Criar um objeto do tipo Especialidade
    Especialidade especialidade = new Especialidade();

    // 2. Coletar dados da tela
    especialidade.setNome(EspelialidadesTextField.getText()); // Substitua pelo nome do seu JTextField
    especialidade.setAtendeConvenio(AtendeConvenioCheckbox.isSelected()); // Substitua pelo nome do seu JCheckBox
     especialidade.setCbo(CBOTextField.getText()); // Substitua pelo nome do seu JCheckBox
    // --- MUDANÇA PRINCIPAL AQUI ---
    // Pega a data do campo de texto que o usuário digitou
    String dataTexto = DataAddMenu.getText(); // Substitua 'campoDataAdicao' pelo nome do seu JTextField
    
    // Define o formato esperado para a data (dia/mês/ano)
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    
    try {
        // Tenta converter o texto em uma data válida
        LocalDate dataAdicao = LocalDate.parse(dataTexto, formato);
        especialidade.setDataAdicao(dataAdicao);
        
        // Se a conversão deu certo, prossegue para salvar
        
        // 3. Criar uma instância do DAO
        EspecialidadeDAO especialidadeDAO = new EspecialidadeDAO();

        // 4. Chamar o método save para persistir os dados
        especialidadeDAO.save(especialidade);

        // 5. Limpar os campos para o próximo cadastro
        limparCamposEspecialidade();

    } catch (DateTimeParseException e) {
        // Se o usuário digitou uma data em formato inválido
        JOptionPane.showMessageDialog(null, "Formato de data inválido. Por favor, use o formato DD/MM/AAAA.");    // TODO add your handling code here:
    }//GEN-LAST:event_AdicionarButtonActionPerformed
            }
    
    private void limparCamposEspecialidade() {
    CBOTextField.setText("");
    EspelialidadesTextField.setText("");
    AtendeConvenioCheckbox.setSelected(false);
    DataAddMenu.setText("");
    // Coloca o foco no campo de nome
    EspelialidadesTextField.requestFocus();
}
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastrarespecialidades().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarButton;
    private javax.swing.JMenu AgendaMenu;
    private javax.swing.JMenu AgendarConsultasMenu;
    private javax.swing.JCheckBox AtendeConvenioCheckbox;
    private javax.swing.JLabel AtendeconveniolabelMenu;
    private javax.swing.JTextField CBOTextField;
    private javax.swing.JLabel CBOlabel;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JLabel DataAddLabel;
    private javax.swing.JTextField DataAddMenu;
    private javax.swing.JLabel EspecialidadeLabel;
    private javax.swing.JMenu Especialidades;
    private javax.swing.JTextField EspelialidadesTextField;
    private javax.swing.JMenu ListarEspelidadesMenu;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    // End of variables declaration//GEN-END:variables
}
