/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

/**
 *
 * @author Alisson Dias
 */
public class Cadastrarespecialidades extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastrarespecialidades.class.getName());

    /**
     * Creates new form Menumain
     */
    public Cadastrarespecialidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        DataAddLabel = new javax.swing.JLabel();
        DataAddMenu = new javax.swing.JTextField();
        MedicoDisponivelLabel = new javax.swing.JLabel();
        EspecialidadeLabel = new javax.swing.JLabel();
        MedicoDisponivelCombobox = new javax.swing.JComboBox<>();
        AtendeconveniolabelMenu = new javax.swing.JLabel();
        CBOlabel = new javax.swing.JLabel();
        EspelialidadesTextField = new javax.swing.JTextField();
        CBOTextField = new javax.swing.JTextField();
        AtendeConvenioCheckbox = new javax.swing.JCheckBox();
        CancelarButton = new javax.swing.JButton();
        AdicionarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        AgendarConsultas = new javax.swing.JMenu();
        AgendarRetornoMenu = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        Especialidades = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        ListarEspelidadesMenu = new javax.swing.JMenu();
        AgendaMenu = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataAddLabel.setText("Data de adição ");

        DataAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataAddMenuActionPerformed(evt);
            }
        });

        MedicoDisponivelLabel.setText("Médico disponivel :");

        EspecialidadeLabel.setText("Especialidade:");

        MedicoDisponivelCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AtendeconveniolabelMenu.setText("Atende por convênio ?");

        CBOlabel.setText("CBO:");

        EspelialidadesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspelialidadesTextFieldActionPerformed(evt);
            }
        });

        CBOTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOTextFieldActionPerformed(evt);
            }
        });

        AtendeConvenioCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendeConvenioCheckboxActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");

        AdicionarButton.setText("Adicionar");

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCadastradosMenu);

        jMenu2.setText("Cadastrar Paciente");
        PacientesMenu.add(jMenu2);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultas.setText("Agendar Consultas");
        jMenuBar1.add(AgendarConsultas);

        AgendarRetornoMenu.setText("Agendar retorno");
        jMenuBar1.add(AgendarRetornoMenu);

        MedicosMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        MedicosMenu.add(CadastrarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicosMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicosMenu);

        Especialidades.setText("Especialidades");

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidade");
        Especialidades.add(CadastrarEspecialidadesMenu);

        ListarEspelidadesMenu.setText("Listar Especialidades");
        Especialidades.add(ListarEspelidadesMenu);

        jMenuBar1.add(Especialidades);

        AgendaMenu.setText("Agenda");
        jMenuBar1.add(AgendaMenu);

        SairMenu.setText("Sair");
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AtendeconveniolabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AtendeConvenioCheckbox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DataAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DataAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MedicoDisponivelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MedicoDisponivelCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AdicionarButton)
                                .addGap(34, 34, 34)
                                .addComponent(CancelarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EspecialidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EspelialidadesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                                .addComponent(CBOlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataAddLabel)
                    .addComponent(DataAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecialidadeLabel)
                    .addComponent(CBOlabel)
                    .addComponent(EspelialidadesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AtendeconveniolabelMenu)
                    .addComponent(AtendeConvenioCheckbox))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicoDisponivelLabel)
                    .addComponent(MedicoDisponivelCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarButton)
                    .addComponent(AdicionarButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataAddMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataAddMenuActionPerformed

    private void CBOTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOTextFieldActionPerformed

    private void AtendeConvenioCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendeConvenioCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtendeConvenioCheckboxActionPerformed

    private void EspelialidadesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspelialidadesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspelialidadesTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastrarespecialidades().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarButton;
    private javax.swing.JMenu AgendaMenu;
    private javax.swing.JMenu AgendarConsultas;
    private javax.swing.JMenu AgendarRetornoMenu;
    private javax.swing.JCheckBox AtendeConvenioCheckbox;
    private javax.swing.JLabel AtendeconveniolabelMenu;
    private javax.swing.JTextField CBOTextField;
    private javax.swing.JLabel CBOlabel;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JLabel DataAddLabel;
    private javax.swing.JTextField DataAddMenu;
    private javax.swing.JLabel EspecialidadeLabel;
    private javax.swing.JMenu Especialidades;
    private javax.swing.JTextField EspelialidadesTextField;
    private javax.swing.JMenu ListarEspelidadesMenu;
    private javax.swing.JComboBox<String> MedicoDisponivelCombobox;
    private javax.swing.JLabel MedicoDisponivelLabel;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    // End of variables declaration//GEN-END:variables
}
