/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;
import Daos.PacienteDAO;
import Entidades.Paciente;
import Utils.ComboBoxManager;
import Login.LoginTela;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisson Dias
 */
public class EditarPaciente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarPaciente.class.getName());
    private PacienteDAO dao = new PacienteDAO();
    private Paciente paciente;
    
      public EditarPaciente(String cpf) {
        initComponents(); // Inicializa os componentes visuais da tela
        
        // Busca os dados completos do paciente no banco de dados
        this.paciente = dao.findByCpf(cpf);
        
        if (this.paciente != null) {
            // Se encontrou o paciente, preenche os campos da tela
            preencherCampos();
        } else {
            // Se, por algum motivo, não encontrou, mostra um erro e fecha a tela
            JOptionPane.showMessageDialog(this, "Paciente com CPF " + cpf + " não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
            dispose(); 
        }
    }
    
    
    /**
     * Creates new form Menumain
     */
    public EditarPaciente() {
        initComponents();
        
        
         ComboBoxManager.preencherComboBoxSexo(SexoComboBox); // Supondo que seu JComboBox se chame 'SexoComboBox'
        ComboBoxManager.preencherComboBoxEstadoCivil(EstadoCivilComboBox); // Supondo que seu JComboBox se chame 'EstadoCivilComboBox'
        ComboBoxManager.preencherComboBoxConvenio(ConvenioComboBox);
        
        
        PacientesCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacientesCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarPacienteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarPacientesMenuMouseClicked(evt);
            }
        });
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() { // Agendar Consultas
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarConsultasMenuMouseClicked(evt);
            }
        });
       
        CadastrarMedicoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMedicoMenuMouseClicked(evt);
            }
        });
        MedicosCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicosCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarEspecialidadesMenuMouseClicked(evt);
            }
        });
        ListarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarEspecialidadesMenuMouseClicked(evt);
            }
        });
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() { // Agenda
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendaMenuMouseClicked(evt);
            }
        });
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() { // Sair
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMenuMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NomeTextfield = new javax.swing.JTextField();
        CpfTextField = new javax.swing.JTextField();
        TelefoneTextField = new javax.swing.JTextField();
        EnderecoTextField = new javax.swing.JTextField();
        EstadoCivilComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        DatadenascimentoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InformaçõesTextArea = new javax.swing.JTextArea();
        SalvarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        ApagarButton = new javax.swing.JButton();
        SexoComboBox = new javax.swing.JComboBox<>();
        ConvenioComboBox = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        CadastrarPacienteMenu = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        MedicoMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        EspecialidadesMenu = new javax.swing.JMenu();
        ListarEspecialidadesMenu = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Cpf");

        jLabel3.setText("Telefone");

        jLabel4.setText("Endereço");

        jLabel5.setText("Sexo");

        jLabel6.setText("Estado Civil");

        EstadoCivilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Data de Nascimento");

        jLabel8.setText("Cônvenio?");

        jLabel9.setText("Informações:");

        InformaçõesTextArea.setColumns(20);
        InformaçõesTextArea.setRows(5);
        jScrollPane1.setViewportView(InformaçõesTextArea);

        SalvarButton.setText("Salvar");
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        ApagarButton.setBackground(new java.awt.Color(255, 0, 0));
        ApagarButton.setText("Apagar");
        ApagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarButtonActionPerformed(evt);
            }
        });

        SexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ConvenioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ConvenioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvenioComboBoxActionPerformed(evt);
            }
        });

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCadastradosMenu);

        CadastrarPacienteMenu.setText("Cadastrar Paciente");
        PacientesMenu.add(CadastrarPacienteMenu);

        jMenuBar1.add(PacientesMenu);

        jMenu4.setText("Agendar Consultas ");
        jMenuBar1.add(jMenu4);

        MedicoMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        MedicoMenu.add(CadastrarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicoMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicoMenu);

        EspecialidadesMenu.setText("Especialidades");

        ListarEspecialidadesMenu.setText("Listar Especialidades");
        EspecialidadesMenu.add(ListarEspecialidadesMenu);

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidades");
        EspecialidadesMenu.add(CadastrarEspecialidadesMenu);

        jMenuBar1.add(EspecialidadesMenu);

        jMenu13.setText("Agenda");
        jMenuBar1.add(jMenu13);

        jMenu3.setText("Sair");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NomeTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(CpfTextField)
                                    .addComponent(TelefoneTextField)
                                    .addComponent(EnderecoTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(SexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatadenascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ConvenioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(SalvarButton)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CancelarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ApagarButton)
                                        .addGap(12, 12, 12))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(EstadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NomeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ConvenioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(EnderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(SexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(DatadenascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EstadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SalvarButton)
                            .addComponent(ApagarButton)
                            .addComponent(CancelarButton))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void PacientesCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
      PacientesCadastradosAtendente PacientesCadastrados = new PacientesCadastradosAtendente ();
    PacientesCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void CadastrarPacientesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
         CadastrarPaciente CadastrarPacientes = new CadastrarPaciente();
    CadastrarPacientes.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void AgendarConsultasMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                  
    
   AgendarCosulta AgendarCosulta  = new AgendarCosulta();
    AgendarCosulta.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                 

   
    private void CadastrarMedicoMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                 
       CadastrarMedico  CadastrarMedico = new  CadastrarMedico();
     CadastrarMedico.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                

    private void MedicosCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        MedicosCadastradosAtendente MedicosCadastrados= new MedicosCadastradosAtendente();
    MedicosCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void CadastrarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                         
        Cadastrarespecialidades Cadastrarespecialidades  =  new Cadastrarespecialidades();
    Cadastrarespecialidades.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                        

    private void ListarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
       EspecialidadeCadastradas  EspecialidadeCadastradas = new EspecialidadeCadastradas();
    EspecialidadeCadastradas.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void AgendaMenuMouseClicked(java.awt.event.MouseEvent evt) {                                        
    Agenda Agenda = new Agenda();
    Agenda.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                       

    private void SairMenuMouseClicked(java.awt.event.MouseEvent evt) {
        String[] options = {"Sim", "Não"};
        int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                "Tem certeza que deseja voltar ao login?",
                "Confirmar Saída", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (confirm == 0) {
            LoginTela LoginTela = new LoginTela();
            LoginTela.setVisible(true); // Torna a tela visível
            this.dispose();
        }
    }   
    
    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonActionPerformed
        // Atualiza o objeto 'paciente' com os novos dados dos campos
        paciente.setNome(NomeTextfield.getText());
        paciente.setTelefone(TelefoneTextField.getText());
        
        // Pegue os outros dados e atualize o objeto...
        
        // Chama o método UPDATE do DAO
        dao.update(paciente);
        
        // Fecha a tela de edição
        dispose();
    
     // TODO add your handling code here:
    }//GEN-LAST:event_SalvarButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void ApagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarButtonActionPerformed
 // Pede confirmação para evitar acidentes
        int resposta = JOptionPane.showConfirmDialog(
            this, 
            "Tem a certeza de que deseja excluir permanentemente o paciente " + paciente.getNome() + "?", 
            "Confirmar Exclusão", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE
        );
        
        if (resposta == JOptionPane.YES_OPTION) {
            // Se o usuário confirmar, chama o método DELETE do DAO
            dao.delete(paciente.getCpf());
            dispose(); // Fecha a tela
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_ApagarButtonActionPerformed

    private void ConvenioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvenioComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConvenioComboBoxActionPerformed
private void preencherCampos() {
        setTitle("Editar Paciente: " + paciente.getNome());

        // Preenche os campos de texto
        CpfTextField.setText(paciente.getCpf());
        CpfTextField.setEditable(false); // IMPORTANTE: O CPF é a chave, não deve ser alterado!
        
        NomeTextfield.setText(paciente.getNome());
        TelefoneTextField.setText(paciente.getTelefone());
        
        // Formata a data para exibir no campo
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        DatadenascimentoTextField.setText(paciente.getDataNascimento().format(formato));
        
        // Preencha outros campos como JComboBox de sexo, etc., se houver
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarPaciente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApagarButton;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JMenu CadastrarPacienteMenu;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JComboBox<String> ConvenioComboBox;
    private javax.swing.JTextField CpfTextField;
    private javax.swing.JTextField DatadenascimentoTextField;
    private javax.swing.JTextField EnderecoTextField;
    private javax.swing.JMenu EspecialidadesMenu;
    private javax.swing.JComboBox<String> EstadoCivilComboBox;
    private javax.swing.JTextArea InformaçõesTextArea;
    private javax.swing.JMenu ListarEspecialidadesMenu;
    private javax.swing.JMenu MedicoMenu;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JTextField NomeTextfield;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JComboBox<String> SexoComboBox;
    private javax.swing.JTextField TelefoneTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
