/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

import Login.LoginTela;

/**
 *
 * @author Alisson Dias
 */
public class EditarCosulta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCosulta.class.getName());

    /**
     * Creates new form Menumain
     */
    public EditarCosulta() {
        initComponents();
        PacientesCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacientesCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarPacinteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarPacientesMenuMouseClicked(evt);
            }
        });
        AgendarConsultasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarConsultasMenuMouseClicked(evt);
            }
        });
        AgendarRetornoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendarRetornoMenuMouseClicked(evt);
            }
        });
        CadastrarMedicoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMedicoMenuMouseClicked(evt);
            }
        });
        MedicosCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicosCadastradosMenuMouseClicked(evt);
            }
        });
        CadastrarEspecialidadeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarEspecialidadesMenuMouseClicked(evt);
            }
        });
        ListarEspecialidadeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListarEspecialidadesMenuMouseClicked(evt);
            }
        });
        Agenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgendaMenuMouseClicked(evt);
            }
        });
        SairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMenuMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        DataLabel = new javax.swing.JLabel();
        DataTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EspecialidadeComboBox = new javax.swing.JComboBox<>();
        EspecialidadesLabel = new javax.swing.JLabel();
        ComboBoxMedico = new javax.swing.JComboBox<>();
        ConvenioLabel = new javax.swing.JLabel();
        ConvenioComboBox = new javax.swing.JComboBox<>();
        PacienteLabelMenu = new javax.swing.JLabel();
        PacienteComboBox = new javax.swing.JComboBox<>();
        SalvarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        ApagarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        CadastrarPacinteMenu = new javax.swing.JMenu();
        AgendarConsultasMenu = new javax.swing.JMenu();
        AgendarRetornoMenu = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        EspecialidadesMenu = new javax.swing.JMenu();
        CadastrarEspecialidadeMenu = new javax.swing.JMenu();
        ListarEspecialidadeMenu = new javax.swing.JMenu();
        Agenda = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DataLabel.setText("Data");

        DataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Medico");

        EspecialidadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EspecialidadesLabel.setText("Especialidade:");

        ComboBoxMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ConvenioLabel.setText("Cônvenio");

        ConvenioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PacienteLabelMenu.setText("Paciente:");

        PacienteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SalvarButton.setText("Salvar");

        CancelarButton.setText("Cancelar");

        ApagarButton.setBackground(new java.awt.Color(255, 0, 0));
        ApagarButton.setText("Apagar");
        ApagarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagarButtonActionPerformed(evt);
            }
        });

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCadastradosMenu);

        CadastrarPacinteMenu.setText("Cadastrar Paciente");
        PacientesMenu.add(CadastrarPacinteMenu);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultasMenu.setText("Agendar Consultas");
        jMenuBar1.add(AgendarConsultasMenu);

        AgendarRetornoMenu.setText("Agendar retorno");
        jMenuBar1.add(AgendarRetornoMenu);

        MedicosMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        MedicosMenu.add(CadastrarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicosMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicosMenu);

        EspecialidadesMenu.setText("Especialidades");

        CadastrarEspecialidadeMenu.setText("Cadastrar Especialidade");
        EspecialidadesMenu.add(CadastrarEspecialidadeMenu);

        ListarEspecialidadeMenu.setText("Listar Especialidades");
        EspecialidadesMenu.add(ListarEspecialidadeMenu);

        jMenuBar1.add(EspecialidadesMenu);

        Agenda.setText("Agenda");
        jMenuBar1.add(Agenda);

        SairMenu.setText("Sair");
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ConvenioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ConvenioComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(ComboBoxMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EspecialidadesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EspecialidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PacienteLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PacienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SalvarButton)
                .addGap(18, 18, 18)
                .addComponent(CancelarButton)
                .addGap(107, 107, 107)
                .addComponent(ApagarButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataLabel)
                    .addComponent(DataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PacienteLabelMenu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComboBoxMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(PacienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EspecialidadesLabel)
                    .addComponent(EspecialidadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvenioLabel)
                    .addComponent(ConvenioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarButton)
                    .addComponent(CancelarButton)
                    .addComponent(ApagarButton))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void PacientesCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
      PacientesCadastradosAtendente PacientesCadastrados = new PacientesCadastradosAtendente ();
    PacientesCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void CadastrarPacientesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
         CadastrarPaciente CadastrarPacientes = new CadastrarPaciente();
    CadastrarPacientes.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void AgendarConsultasMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                  
    
   AgendarCosulta AgendarCosulta  = new AgendarCosulta();
    AgendarCosulta.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                 

    private void AgendarRetornoMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                
     Agendarretorno Agendarretorno = new Agendarretorno();
    Agendarretorno.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                               

    private void CadastrarMedicoMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                 
       CadastrarMedico  CadastrarMedico = new  CadastrarMedico();
     CadastrarMedico.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                

    private void MedicosCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        MedicosCadastradosAtendente MedicosCadastrados= new MedicosCadastradosAtendente();
    MedicosCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void CadastrarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                         
        Cadastrarespecialidades Cadastrarespecialidades  =  new Cadastrarespecialidades();
    Cadastrarespecialidades.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                        

    private void ListarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
       EspecialidadeCadastradas  EspecialidadeCadastradas = new EspecialidadeCadastradas();
    EspecialidadeCadastradas.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void AgendaMenuMouseClicked(java.awt.event.MouseEvent evt) {                                        
    Agenda Agenda = new Agenda();
    Agenda.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                       

    private void SairMenuMouseClicked(java.awt.event.MouseEvent evt) {
        String[] options = {"Sim", "Não"};
        int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                "Tem certeza que deseja voltar ao login?",
                "Confirmar Saída", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (confirm == 0) {
            LoginTela LoginTela = new LoginTela();
            LoginTela.setVisible(true); // Torna a tela visível
            this.dispose();
        }
    }   
    
    private void DataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataTextFieldActionPerformed

    private void ApagarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApagarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarCosulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agenda;
    private javax.swing.JMenu AgendarConsultasMenu;
    private javax.swing.JMenu AgendarRetornoMenu;
    private javax.swing.JButton ApagarButton;
    private javax.swing.JMenu CadastrarEspecialidadeMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JMenu CadastrarPacinteMenu;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JComboBox<String> ComboBoxMedico;
    private javax.swing.JComboBox<String> ConvenioComboBox;
    private javax.swing.JLabel ConvenioLabel;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JTextField DataTextField;
    private javax.swing.JComboBox<String> EspecialidadeComboBox;
    private javax.swing.JLabel EspecialidadesLabel;
    private javax.swing.JMenu EspecialidadesMenu;
    private javax.swing.JMenu ListarEspecialidadeMenu;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JComboBox<String> PacienteComboBox;
    private javax.swing.JLabel PacienteLabelMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    // End of variables declaration//GEN-END:variables
}
