/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

import Daos.EspecialidadeDAO;
import Entidades.Especialidade;
import Login.LoginTela;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alisson Dias
 */
public class EspecialidadeCadastradas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EspecialidadeCadastradas.class.getName());

    /**
     * Creates new form Menumain
     */
    public EspecialidadeCadastradas() {
        initComponents();

        
        preencherTabelaEspecialidades();
        
        
        
            PacientesCaastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    PacientesCadastradosMenuMouseClicked(evt);
                }
            });
            CadastrarPacienteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    CadastrarPacientesMenuMouseClicked(evt);
                }
            });
            AgendarConsultasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    AgendarConsultasMenuMouseClicked(evt);
                }
            });
            
            CadastarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    CadastrarMedicoMenuMouseClicked(evt);
                }
            });
            MedicosCadastradosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    MedicosCadastradosMenuMouseClicked(evt);
                }
            });
            CadastrarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    CadastrarEspecialidadesMenuMouseClicked(evt);
                }
            });
            ListarEspecialidadesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ListarEspecialidadesMenuMouseClicked(evt);
                }
            });
            AgendaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    AgendaMenuMouseClicked(evt);
                }
            });
            SairMenu.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    SairMenuMouseClicked(evt);
                }
            });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        EspecialidadesTable = new javax.swing.JTable();
        EditarEspecialidadeButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCaastradosMenu = new javax.swing.JMenu();
        CadastrarPacienteMenu = new javax.swing.JMenu();
        AgendarConsultasMenu = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastarMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        EspecialidadesMenu = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        ListarEspecialidadesMenu = new javax.swing.JMenu();
        AgendaMenu = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EspecialidadesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Medicos disponiveis", "Convenio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(EspecialidadesTable);

        EditarEspecialidadeButton.setText("Editar especialidade");

        PacientesMenu.setText("Pacientes");

        PacientesCaastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCaastradosMenu);

        CadastrarPacienteMenu.setText("Cadastrar Paciente");
        PacientesMenu.add(CadastrarPacienteMenu);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultasMenu.setText("Agendar Consultas");
        jMenuBar1.add(AgendarConsultasMenu);

        MedicosMenu.setText("Médicos");

        CadastarMenu.setText("Cadastrar Médico");
        MedicosMenu.add(CadastarMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicosMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicosMenu);

        EspecialidadesMenu.setText("Especialidades");

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidades");
        EspecialidadesMenu.add(CadastrarEspecialidadesMenu);

        ListarEspecialidadesMenu.setText("Listar Especialidades");
        EspecialidadesMenu.add(ListarEspecialidadesMenu);

        jMenuBar1.add(EspecialidadesMenu);

        AgendaMenu.setText("Agenda");
        jMenuBar1.add(AgendaMenu);

        SairMenu.setText("Sair");
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditarEspecialidadeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarEspecialidadeButton)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void preencherTabelaEspecialidades() {
        // Pega o modelo da JTable. Substitua 'jTableEspecialidades' pelo nome da sua tabela.
        DefaultTableModel modelo = (DefaultTableModel) EspecialidadesTable.getModel();
        modelo.setRowCount(0); // Limpa a tabela para não duplicar dados ao recarregar

        EspecialidadeDAO edao = new EspecialidadeDAO();
        List<Especialidade> listaEspecialidades = edao.findAll();
        
        DateTimeFormatter formatadorData = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Itera sobre a lista de especialidades retornada pelo DAO
        for (Especialidade e : listaEspecialidades) {
            
            // Lógica para converter o valor booleano em um texto "Sim" ou "Não"
            String atendeConvenioTexto = e.isAtendeConvenio() ? "Sim" : "Não";
            
            // Adiciona uma nova linha na tabela com os dados formatados
            modelo.addRow(new Object[]{
                e.getCbo(),
                e.getNome(),
                atendeConvenioTexto, // Usa o texto formatado
                e.getDataAdicao().format(formatadorData) // Usa a data formatada
            });
        }
    }
    
    
    
    
    
     private void PacientesCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
      PacientesCadastradosAtendente PacientesCadastrados = new PacientesCadastradosAtendente ();
    PacientesCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void CadastrarPacientesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
         CadastrarPaciente CadastrarPacientes = new CadastrarPaciente();
    CadastrarPacientes.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void AgendarConsultasMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                  
    
   AgendarCosulta AgendarCosulta  = new AgendarCosulta();
    AgendarCosulta.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                 

                                           

    private void CadastrarMedicoMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                 
       CadastrarMedico  CadastrarMedico = new  CadastrarMedico();
     CadastrarMedico.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                

    private void MedicosCadastradosMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        MedicosCadastradosAtendente MedicosCadastrados= new MedicosCadastradosAtendente();
    MedicosCadastrados.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                   

    private void CadastrarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                         
        Cadastrarespecialidades Cadastrarespecialidades  =  new Cadastrarespecialidades();
    Cadastrarespecialidades.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                        

    private void ListarEspecialidadesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                                      
       EspecialidadeCadastradas  EspecialidadeCadastradas = new EspecialidadeCadastradas();
    EspecialidadeCadastradas.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                                     

    private void AgendaMenuMouseClicked(java.awt.event.MouseEvent evt) {                                        
    Agenda Agenda = new Agenda();
    Agenda.setVisible(true); // Torna a tela visível
    this.dispose();
    }                                       

    private void SairMenuMouseClicked(java.awt.event.MouseEvent evt) {
        String[] options = {"Sim", "Não"};
        int confirm = javax.swing.JOptionPane.showOptionDialog(this,
                "Tem certeza que deseja voltar ao login?",
                "Confirmar Saída", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null, options, options[0]);
        if (confirm == 0) {
            LoginTela LoginTela = new LoginTela();
            LoginTela.setVisible(true); // Torna a tela visível
            this.dispose();
        }
        
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EspecialidadeCadastradas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgendaMenu;
    private javax.swing.JMenu AgendarConsultasMenu;
    private javax.swing.JMenu CadastarMenu;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarPacienteMenu;
    private javax.swing.JButton EditarEspecialidadeButton;
    private javax.swing.JMenu EspecialidadesMenu;
    private javax.swing.JTable EspecialidadesTable;
    private javax.swing.JMenu ListarEspecialidadesMenu;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JMenu PacientesCaastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
