/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

/**
 *
 * @author Alisson Dias
 */
public class EspecialidadeCadastradas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EspecialidadeCadastradas.class.getName());

    /**
     * Creates new form Menumain
     */
    public EspecialidadeCadastradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        EditarEspecialidadeButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        CadastrarPacientesMenu = new javax.swing.JMenu();
        AgendarConsultasMenu = new javax.swing.JMenu();
        AgendaRetornoMenu = new javax.swing.JMenu();
        Medicos = new javax.swing.JMenu();
        CadrastarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        Especialidades = new javax.swing.JMenu();
        CadastrarEspecialidasdes = new javax.swing.JMenu();
        ListarEspecialidar = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();
        Agenda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Medicos disponiveis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        EditarEspecialidadeButton.setText("Editar especialidade");

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCadastradosMenu);

        CadastrarPacientesMenu.setText("Cadastrar Paciente");
        PacientesMenu.add(CadastrarPacientesMenu);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultasMenu.setText("Agendar Consultas");
        jMenuBar1.add(AgendarConsultasMenu);

        AgendaRetornoMenu.setText("Agendar retorno");
        jMenuBar1.add(AgendaRetornoMenu);

        Medicos.setText("Médicos");

        CadrastarMedicoMenu.setText("Cadastrar Médico");
        Medicos.add(CadrastarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        Medicos.add(MedicosCadastradosMenu);

        jMenuBar1.add(Medicos);

        Especialidades.setText("Especialidades");

        CadastrarEspecialidasdes.setText("Cadastrar Especialidades");
        Especialidades.add(CadastrarEspecialidasdes);

        ListarEspecialidar.setText("Listar Especialidades");
        Especialidades.add(ListarEspecialidar);

        jMenuBar1.add(Especialidades);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenuBar1.add(Sair);

        Agenda.setText("Agenda");
        jMenuBar1.add(Agenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditarEspecialidadeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarEspecialidadeButton)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
       dispose();
    }//GEN-LAST:event_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EspecialidadeCadastradas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Agenda;
    private javax.swing.JMenu AgendaRetornoMenu;
    private javax.swing.JMenu AgendarConsultasMenu;
    private javax.swing.JMenu CadastrarEspecialidasdes;
    private javax.swing.JMenu CadastrarPacientesMenu;
    private javax.swing.JMenu CadrastarMedicoMenu;
    private javax.swing.JButton EditarEspecialidadeButton;
    private javax.swing.JMenu Especialidades;
    private javax.swing.JMenu ListarEspecialidar;
    private javax.swing.JMenu Medicos;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
