/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtendenteTelas;

/**
 *
 * @author Alisson Dias
 */
public class PacientesCadastradosAtendente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PacientesCadastradosAtendente.class.getName());

    /**
     * Creates new form Menumain
     */
    public PacientesCadastradosAtendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        PacientesTable = new javax.swing.JTable();
        EditarPacientesCadastradosButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        PacientesMenu = new javax.swing.JMenu();
        PacientesCadastradosMenu = new javax.swing.JMenu();
        CadastrarPacientesMenu = new javax.swing.JMenu();
        AgendarConsultasMenu = new javax.swing.JMenu();
        AgendarRetorno = new javax.swing.JMenu();
        MedicosMenu = new javax.swing.JMenu();
        CadastrarMedicoMenu = new javax.swing.JMenu();
        MedicosCadastradosMenu = new javax.swing.JMenu();
        EspecialideMenu = new javax.swing.JMenu();
        CadastrarEspecialidadesMenu = new javax.swing.JMenu();
        ListarEspecialidadeMenu = new javax.swing.JMenu();
        AgendaMenu = new javax.swing.JMenu();
        SairMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PacientesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Cpf", "Telefone", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PacientesTable);

        EditarPacientesCadastradosButton.setText("Editar Pacientes Cadastrados");
        EditarPacientesCadastradosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPacientesCadastradosButtonActionPerformed(evt);
            }
        });

        PacientesMenu.setText("Pacientes");

        PacientesCadastradosMenu.setText("Pacientes Cadastrados");
        PacientesMenu.add(PacientesCadastradosMenu);

        CadastrarPacientesMenu.setText("Cadastrar Paciente");
        PacientesMenu.add(CadastrarPacientesMenu);

        jMenuBar1.add(PacientesMenu);

        AgendarConsultasMenu.setText("Agendar Consultas");
        jMenuBar1.add(AgendarConsultasMenu);

        AgendarRetorno.setText("Agendar retorno");
        jMenuBar1.add(AgendarRetorno);

        MedicosMenu.setText("Médicos");

        CadastrarMedicoMenu.setText("Cadastrar Médico");
        MedicosMenu.add(CadastrarMedicoMenu);

        MedicosCadastradosMenu.setText("Médicos Cadastrados");
        MedicosMenu.add(MedicosCadastradosMenu);

        jMenuBar1.add(MedicosMenu);

        EspecialideMenu.setText("Especialidades");

        CadastrarEspecialidadesMenu.setText("Cadastrar Especialidades");
        EspecialideMenu.add(CadastrarEspecialidadesMenu);

        ListarEspecialidadeMenu.setText("Listar Especialidades");
        EspecialideMenu.add(ListarEspecialidadeMenu);

        jMenuBar1.add(EspecialideMenu);

        AgendaMenu.setText("Agenda");
        jMenuBar1.add(AgendaMenu);

        SairMenu.setText("Sair");
        jMenuBar1.add(SairMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditarPacientesCadastradosButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditarPacientesCadastradosButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarPacientesCadastradosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPacientesCadastradosButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarPacientesCadastradosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PacientesCadastradosAtendente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AgendaMenu;
    private javax.swing.JMenu AgendarConsultasMenu;
    private javax.swing.JMenu AgendarRetorno;
    private javax.swing.JMenu CadastrarEspecialidadesMenu;
    private javax.swing.JMenu CadastrarMedicoMenu;
    private javax.swing.JMenu CadastrarPacientesMenu;
    private javax.swing.JButton EditarPacientesCadastradosButton;
    private javax.swing.JMenu EspecialideMenu;
    private javax.swing.JMenu ListarEspecialidadeMenu;
    private javax.swing.JMenu MedicosCadastradosMenu;
    private javax.swing.JMenu MedicosMenu;
    private javax.swing.JMenu PacientesCadastradosMenu;
    private javax.swing.JMenu PacientesMenu;
    private javax.swing.JTable PacientesTable;
    private javax.swing.JMenu SairMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
